import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { UiThemeProvider } from "@/providers/ui-theme-provider";

const dmSans = DM_Sans({
  variable: "--font-dm-sans", // Custom CSS variable
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmSans.variable} ${dmSans.variable}`}>
        <UiThemeProvider>{children}</UiThemeProvider>
      </body>
    </html>
  );
}
